// AUTO-PORTED from the Credit OS design bundle (shared/deal-modules.js).
// ATLF demo data — replace with live module outputs when CP backend persistence lands.
// [code, required output, status, note?]  status: ok | warning | gap
export type StepRow = (string | undefined)[];
export const STEP_STATUS_TEXT: Record<string, string> = { ok: "produced", warning: "produced w/ limitation", gap: "gap logged" };

export const MODULE_STEPS: Record<string, StepRow[]> = {
    "CP-0": [
      ["A", "File Classification", "ok", "14 files typed"], ["B", "Entity Identification", "ok"],
      ["C", "Document Mapping", "ok"], ["D", "Quality Assignment", "ok", "grades A–C"],
      ["E", "Content-Module Mapping", "ok"], ["F", "Gap Logging", "warning", "G-01 · G-02 logged"],
      ["G", "Conflict Logging", "ok", "0 unresolved"], ["H", "File Quality Risk", "ok"],
      ["I", "Downstream Readiness", "ok", "0.91"], ["J", "Master Index Update", "ok"], ["K", "Export Assembly", "ok"],
    ],
    "CP-X": [
      ["TX.1", "Route Plan Source Gate", "warning", "ready with limitations"], ["TX.2", "Module Execution Sequence", "ok", "8 waves"],
      ["TX.3", "Module Readiness Register", "ok", "21 GREEN"], ["TX.4", "One-Owner-Per-Object Validation", "ok", "0 collisions"],
      ["TX.5", "Source-to-Module Routing Map", "ok"], ["TX.6", "Limitation Propagation Register", "warning", "L-04 → CP-2F · CP-6A"],
      ["TX.7", "Route Plan Summary", "ok"],
    ],
    "CP-1": [
      ["T4.1", "Source Register (file gate)", "ok"], ["T4.2", "Entity / Period Key", "ok"],
      ["T4.3", "Normalization Register", "ok"], ["T4.4", "Income Statement Coverage", "ok"],
      ["T4.5", "Cash Flow Statement Coverage", "ok"], ["T4.6", "Balance Sheet Coverage", "ok"],
      ["T4.7", "Normalized Financials Table", "ok"], ["T4.8", "Derived Period Register", "warning", "Q4-25 from sponsor model (G-02)"],
      ["T4.9", "Calc Register + KPI Build", "ok", "41 KPIs"], ["T4.11", "Definition Conflict Register", "warning", "2 conflicts logged"],
      ["—", "Evidence→Risk→Credit Narrative", "ok"], ["T4.12", "Gaps + Downstream Readiness", "ok", "GREEN"],
    ],
    "CP-1A": [
      ["1", "Source Basis Establishment", "ok"], ["2", "Source Classification", "ok"],
      ["3", "Transaction Summary", "ok"], ["4", "Business Description", "ok"],
      ["5", "Ownership Register", "ok", "Kestrel 68.4%"], ["6", "Operating Model", "ok"],
      ["7", "History / Timeline", "ok"], ["8", "Credit Translation", "ok"],
      ["9", "Gaps Ledger", "ok"], ["10", "Module Summary", "ok"],
    ],
    "CP-1B": [
      ["1", "File Gate & Source Validation", "ok"], ["2", "Issuer / Period Scope", "ok"],
      ["3", "Definition Inheritance", "ok", "CP-1 defs preserved"], ["4", "Summary Top Sheet", "ok"],
      ["5", "Financial Performance Table", "ok"], ["6", "KPI Dashboard", "ok"],
      ["7", "Variance Analysis", "warning", "−4.2% vs sponsor model"], ["8", "Corporate Actions", "ok", "2 actions"],
      ["9", "Comparative Evaluation", "ok"], ["10", "Conflict Log", "warning", "model variance logged to CP-5"],
      ["11", "Monitoring Assessment", "ok"], ["12", "Gaps & Limitations Ledger", "ok"], ["13", "Overall Earnings View", "ok"],
    ],
    "CP-1C": [
      ["0", "Peer Discovery Gate", "ok"], ["1", "Peer Data Gate", "ok"],
      ["2", "Peer Universe Register", "ok", "7 names"], ["3", "Metric Alignment Register", "warning", "E-44 anchor mismatch (QA-117)"],
      ["4A", "Operating Benchmark", "ok"], ["4B", "Cash Flow & Capital Intensity", "ok"],
      ["4C", "Credit Metric Benchmark", "ok"], ["4D", "Summary Statistics", "ok"],
      ["5", "Outlier Register", "ok", "Tarn excluded"], ["6A", "Public Trading Comps", "ok"],
      ["6B", "Transaction Comps", "warning", "thin set — 2 datapoints"], ["6C", "Implied EV", "ok"],
      ["7", "Peer Interpretation & Credit Translation", "ok"], ["8", "Gaps & Limitations Ledger", "ok"], ["9", "Overall Peer Benchmarking View", "ok"],
    ],
    "CP-2": [
      ["1", "Source Gate & Readiness", "ok"], ["2", "Company Description", "ok"],
      ["3", "Ownership & Group Structure", "ok"], ["4A", "Revenue Drivers & Pricing Power", "ok"],
      ["4B", "Cost Structure & Margin Resilience", "ok"], ["4C", "Capital Intensity & FCF Conversion", "ok"],
      ["5A", "Porter Five Forces", "ok"], ["5B", "PEST Analysis", "ok"], ["5C", "SWOT Analysis", "ok"],
      ["6", "Key Strengths & Weaknesses", "ok"], ["7", "Financial Profile & Credit Quality", "ok", "9-dim scorecard"],
      ["8", "Outlook, Tailwinds & Headwinds", "ok"], ["9", "Qualitative Downside Scenario", "ok"],
      ["10", "Materiality Filter", "ok"], ["11", "Issuer Matrix", "ok", "6 factors"],
      ["12", "Monitoring Triggers", "ok", "4 set"], ["13", "Overall Credit View", "ok"],
    ],
    "CP-2B": [
      ["1", "Source Gate & Baseline", "ok"], ["2", "Business Model Snapshot", "ok"],
      ["3", "Fragility Map", "ok", "F-1…F-4"], ["4", "Stress Transmission Table", "ok"],
      ["5", "Downside Pathway Register", "ok", "3 pathways"], ["6", "Downside Sensitivity Matrix", "ok"],
      ["7", "Monitoring Sensitivity Flags", "ok"], ["8", "Cross-Module Handoff Register", "ok", "→ CP-3D · CP-6A · CP-6E"],
      ["9", "Gaps Ledger", "ok"], ["10", "Overall Downside Pathway View", "ok"],
    ],
    "CP-2C": [
      ["1", "Source Gate & Calendar Scope", "ok"], ["T5.1", "Event Source Register", "ok"],
      ["T5.2", "Catalyst Calendar", "ok", "9 events"], ["T5.3", "Event Risk Register", "ok"],
      ["T5.4", "Probability-Impact Matrix", "ok"], ["T5.5", "Monitoring Priority Table", "ok"],
      ["T5.6", "Watchlist Handoff Register", "ok", "3 handoffs"], ["T5.7", "Gaps & Limitations Ledger", "ok"], ["—", "Overall Catalyst View", "ok"],
    ],
    "CP-2D": [
      ["T2D.1", "Source Register & Readiness", "ok"], ["T2D.2", "Ownership & Control Register", "ok"],
      ["T2D.3", "Governance Register", "ok", "1 of 7 independent"], ["T2D.4", "Behavior Flag Register", "warning", "2 flags — recap history · RP pre-positioning"],
      ["T2D.5", "Capital Allocation Risk Table", "ok"], ["T2D.6", "Acquisition Appetite Table", "ok"],
      ["T2D.7", "Disclosure Quality Log", "ok", "B+"], ["T2D.8", "Creditor Alignment Table", "ok"],
      ["T2D.9", "Sponsor Risk Assessment", "ok", "MODERATE-HIGH"], ["T2D.10", "Cross-Module Handoff Register", "ok"],
      ["T2D.11", "Gaps Ledger", "ok"], ["T2D.12", "Overall Governance View", "ok"],
    ],
    "CP-2E": [
      ["T2E.1", "Source Register & Module Status", "ok"], ["T2E.2", "Beginning Liquidity Register", "ok", "$379M accessible"],
      ["T2E.3", "Mandatory Cash Uses Register", "ok"], ["T2E.4", "WC & Capex Pressure Table", "ok"],
      ["T2E.5", "12-Month Liquidity Bridge", "ok", "+$96M"], ["T2E.6", "Months to Empty Result", "ok", "19.3 / 14.0 stress"],
      ["T2E.7", "Mitigants & Constraints Table", "ok"], ["—", "Liquidity Risk Level + Narrative", "ok", "ADEQUATE"],
      ["T2E.9", "Gaps Ledger", "ok"], ["—", "Overall Liquidity View", "ok"],
    ],
    "CP-2F": [
      ["T2F.1", "Source Register & Module Status", "warning", "ready with limitations (G-01)"], ["T2F.2", "Debt & Rate Exposure Register", "ok"],
      ["T2F.3", "Hedging Register", "gap", "not provided — limitation L-04"], ["T2F.4", "Unhedged Floating Exposure", "warning", "modeled from SFA only"],
      ["T2F.5", "+100bps Rate Sensitivity", "warning", "−$12.1M on unhedged assumption"], ["T2F.6", "FX Exposure Register", "ok", "LOW"],
      ["T2F.7", "Commodity & Inflation Table", "ok", "pass-through 60–90d"], ["T2F.8", "Macro Sensitivity Summary", "ok"],
      ["T2F.9", "Gaps Ledger", "ok", "G-01"], ["T2F.10", "Overall Macro / Hedging View", "ok"],
    ],
    "CP-2G": [
      ["T2G.1", "Source Register", "gap", "Live run required — no reference finding"],
      ["T2G.2", "Transition Risk Register", "gap", "Live output only"],
      ["T2G.3", "Social Event-Risk Register", "gap", "Live output only"],
      ["T2G.4", "Materiality Table", "gap", "Live output only"],
      ["T2G.5", "KPI / SPT / Ratchet Table", "gap", "Live output only"],
      ["T2G.6", "Demand / Access Implications", "gap", "Live output only"],
      ["T2G.7", "ESG Credit Implication Table", "gap", "Live output only"],
      ["T2G.8", "Gaps Ledger", "gap", "Live output only"],
      ["—", "Overall Credit View & CP-6A Handoff", "gap", "Live output only"],
    ],
    "CP-3": [
      ["T3.1", "Source Register + Execution Mode", "ok"], ["—", "Fundamental Credit Summary", "ok"],
      ["T3.3", "Issuer / Security Scorecard", "ok", "71 / 100"], ["T3.4", "Override Review", "ok", "0 overrides"],
      ["T3.5", "Relative Value Table", "warning", "ex-E-44 band carried"], ["T3.6", "Fundamental Value Matrix", "ok"],
      ["T3.7", "Final Ranking", "ok", "2 of 7"], ["—", "Security Selection Conclusions", "ok"],
      ["T3.9", "Monitoring Triggers", "ok"], ["T3.10", "Gaps Ledger", "ok"], ["—", "Final Credit / RV View", "ok"],
    ],
    "CP-3B": [
      ["T3B.1", "Instrument Data Gate", "ok"], ["T3B.2", "Capital Structure Dashboard", "ok"],
      ["T3B.3", "Instrument Matrix", "ok"], ["T3B.4", "Structural Positioning Log", "ok"],
      ["T3B.5", "Legal / Covenant / LME Overlay", "ok"], ["T3B.6", "Recovery Sensitivity Table", "ok", "5.0–7.5x grid"],
      ["T3B.7", "Compensation Cross-Check", "ok"], ["T3B.8", "Preference Decision Table", "ok", "2L TL over TLB"],
      ["—", "Ranking & Trade-Off Summary", "ok"], ["T3B.10", "Monitoring Triggers", "ok"],
      ["T3B.11", "Gaps Ledger", "ok"], ["—", "Overall Instrument Preference View", "ok"],
    ],
    "CP-3C": [
      ["T3C.1", "Portfolio Input Gate", "ok"], ["T3C.2", "Portfolio Fit Register", "ok"],
      ["T3C.3", "Position Sizing Posture Table", "ok"], ["T3C.4", "Risk Budget Flags", "warning", "B3 bucket 91% utilized"],
      ["T3C.5", "Concentration & Correlation Register", "ok"], ["T3C.6", "Liquidity & Implementation", "ok"],
      ["T3C.7", "Downside Budget & Recovery Sensitivity", "ok"], ["T3C.8", "Monitoring / Add-Trim Triggers", "ok"],
      ["T3C.9", "Gaps Ledger", "ok"], ["—", "Overall Portfolio Fit View", "ok"],
    ],
    "CP-3D": [
      ["T3D.1", "Source Register & Module Status", "ok"], ["T3D.2", "Maturity Wall Register", "ok"],
      ["T3D.3", "Liquidity / Market Access Table", "ok"], ["T3D.4", "Legal Capacity for LME", "warning", "uptier path OPEN"],
      ["T3D.5", "Sponsor Willingness Table", "ok"], ["T3D.6", "Refinancing Path Table", "ok"],
      ["T3D.7", "Vulnerability Score Table", "ok", "4 / 10"], ["T3D.8", "Creditor Class Exposure Table", "ok"],
      ["T3D.9", "Monitoring Triggers", "ok"], ["T3D.10", "Scenario Map (base / stress / LME)", "ok"],
      ["T3D.11", "Gaps Ledger", "ok"], ["—", "Overall Refinancing / LME View", "ok"],
    ],
    "CP-4": [
      ["T4.1", "Source Gate + Module Status", "ok"], ["T4.2", "Controlling Document Register", "ok", "executed docs control"],
      ["T4.3", "Covenant Feature Register", "ok", "41 provisions"], ["—", "EBITDA, Definitions & Ratio Mechanics", "ok"],
      ["—", "Debt Incurrence, Incremental & MFN", "ok"], ["—", "Leakage, RP, Investments & Transfers", "ok"],
      ["—", "Collateral, Guarantees & Subordination", "ok"], ["—", "EoD, Remedies & Amendment Risk", "ok"],
      ["T4.9", "PD vs LGD / Recovery Translation", "ok"], ["T4.10", "Market Norm Comparison", "ok", "vs 6.1 norm"],
      ["T4.11", "Aggressiveness Score", "ok", "7.2 / 10 — Aggressive"], ["T4.12", "Red Flags & Monitoring Triggers", "warning", "MFN sunset · RP capacity"],
      ["T4.13", "Gaps Ledger", "ok"], ["—", "Overall Legal Credit View", "ok"],
    ],
    "CP-4D": [
      ["T4D.1", "Source Gate Register", "gap", "Live run required — no reference finding"],
      ["T4D.2", "Restricted / Unrestricted Entity Register", "gap", "Live output only"],
      ["T4D.3", "Guarantor Coverage Matrix", "gap", "Live output only"],
      ["T4D.4", "Collateral-by-Entity Matrix", "gap", "Live output only"],
      ["T4D.5", "Structural Priority Table", "gap", "Live output only"],
      ["T4D.6", "Drop-down / Transfer Capacity Register", "gap", "Live output only"],
      ["T4D.7", "Priming-Exposure Findings", "gap", "Live output only"],
      ["T4D.8", "Gaps Ledger", "gap", "Live output only"],
      ["—", "Overall Structural View & Handoffs", "gap", "Live output only"],
    ],
    "CP-4C": [
      ["T4C.1", "Source Gate + Module Status", "ok"], ["T4C.2", "Controlling Capacity Source Map", "ok"],
      ["T4C.3", "Definition & Ratio Mechanics Register", "ok"], ["T4C.4", "Headroom Table", "ok"],
      ["T4C.5", "Capacity Register", "ok", "$612M day-one"], ["T4C.6", "Debt / Lien / Priming Analysis", "warning", "priming MEDIUM-HIGH"],
      ["T4C.7", "RP / Leakage Analysis", "warning", "$240M builder basket"], ["T4C.8", "Add-Back Inflation Analysis", "warning", "18.2% of adj. EBITDA"],
      ["T4C.9", "Leakage & Basket Flags", "ok"], ["—", "Nearest Pressure Point", "ok", "MFN sunset Jun-27"],
      ["T4C.11", "Capacity Risk Priority Matrix", "ok"], ["T4C.12", "Gaps Ledger", "ok"], ["—", "Overall Covenant Capacity View", "ok"],
    ],
    "CP-5": [
      ["T5.1", "Input Module Register", "ok", "24 modules"], ["T5.2", "Citation & Evidence Audit", "warning", "QA-117 HIGH open"],
      ["T5.3", "Math / Logic / Definition Audit", "ok", "0 defects"], ["T5.4", "Legal / Structural Claim Audit", "ok"],
      ["T5.5", "RV / Market Claim Audit", "ok"], ["T5.6", "Consistency & Version Audit", "ok"],
      ["T5.7", "Committee-Readiness Audit", "warning", "pack HELD"], ["T5.8", "Export & Evidence Trace Audit", "ok"],
      ["T5.9", "Consolidated Issue Log", "ok", "1 HIGH · 2 LOW"], ["—", "Remediation Priority Map", "ok"],
      ["—", "Clearance Decision", "warning", "CONDITIONAL"],
    ],
    "CP-5B": [
      ["T5B.1", "Source Register & Readiness", "ok"], ["T5B.2", "Top-5 Material Credit Drivers", "ok"],
      ["T5B.3", "Traceability Map", "ok"], ["T5B.4", "Source Lineage Register", "ok"],
      ["T5B.5", "Calculation & Assumption Register", "ok"], ["T5B.6", "Weak-Lineage Flags", "warning", "driver #5 (E-44)"],
      ["T5B.7", "Auditability Assessment", "ok", "STRONG"], ["T5B.8", "Gaps Ledger", "ok"], ["—", "Overall Traceability View", "ok"],
    ],
    "CP-6A": [
      ["—", "IC Debate Source Gate", "ok"], ["—", "Pre-Debate Thesis Map", "ok"],
      ["—", "Bull Opening Statement", "ok", "3 claims"], ["T6A.4", "Bear Cross-Examination", "ok", "4 attacks"],
      ["—", "Bull Defense", "ok", "1 concession (E-44)"], ["T6A.6", "Chair Evidence Weighting", "ok", "5 claims scored"],
      ["T6A.7", "Debate Resolution Matrix", "ok"], ["—", "Action Bias Determination", "ok", "CONSTRUCTIVE — add on weakness"],
      ["—", "Single Greatest Uncertainty", "ok", "add-back realization"], ["—", "IC Chair Final Memo", "ok"],
      ["T6A.11", "Gaps Ledger", "ok"],
    ],
    "CP-6E": [
      ["—", "Portfolio Debate Source Gate", "ok"], ["—", "Pre-Debate Portfolio Thesis Map", "ok"],
      ["—", "RV Trader's Pitch", "ok", "3 bullets"], ["T6E.4", "Compliance Officer's Attack", "ok"],
      ["—", "RV Trader's Defense", "ok", "sizing constraint proposed"], ["T6E.6", "CIO Evidence Weighting", "ok"],
      ["T6E.7", "Allocation Decision Matrix", "ok"], ["—", "Final Sizing Posture", "ok", "75 → 125bps"],
      ["—", "Exact Portfolio Constraint", "ok", "B3 bucket headroom"], ["—", "CIO Final Memo", "ok"],
      ["T6E.11", "Gaps Ledger", "ok"],
    ],
  };
