// AUTO-PORTED from the Credit OS design bundle (shared/deal-modules.js + deal-step-notes.js).
// ATLF demo data — replace with live module outputs when CP backend persistence lands.
/* eslint-disable */

export interface StepNote { body: string; ev?: string[] }

const BASE: Record<string, StepNote> = {
    "CP-0:Gap Logging": { body: "Two gaps logged at intake. G-01 (hedging register / swap confirms) degrades CP-2F to SFA-margin modeling and propagates as limitation L-04. G-02 (Q4-25 management accounts) forces CP-1 to construct Q4-25 as a derived period from the sponsor model at [Analyst estimate] status. Neither gap blocks the route; both carry degraded-mode instructions and re-request dates (Jun 04)." },
    "CP-0:Downstream Readiness": { body: "Readiness scored 0.91 against the 0.85 full-run threshold. All 21 analytical modules are routable; CP-2F is the only consumer entering degraded mode. The readiness register, master index and intake export were assembled and handed to CP-X." },
    "CP-X:Route Plan Source Gate": { body: "Gate status READY WITH LIMITATIONS — CP-0 readiness 0.91 admits a full run, with G-01 carried as limitation L-04 rather than a blocker. Route template v2.2 selected for a new-issue committee review." },
    "CP-X:Limitation Propagation Register": { body: "L-04 (no hedging register) attaches to every CP-2F output object and surfaces to CP-6A so the Chair weights macro claims accordingly. G-02 attaches a derived-period caveat to CP-1 T4.8 and to CP-1B quarterly comparisons." },
    "CP-X:Route Plan Summary": { body: "21 modules sequenced across 8 waves; one-owner-per-object validation clean (0 collisions); the J1 join holds the debate layer until every analytical feeder lands. Expected wall-clock ~46 minutes at current concurrency." },
    "CP-1:Normalization Register": { body: "12 periods normalized to a single chart of accounts with FX, 53-week and discontinued-ops adjustments logged line-by-line, each with an audit-trail reference. Tie-out to audited financials within 0.3% on every line." },
    "CP-1:Derived Period Register": { ev: ["E-58"], body: "Q4-25 constructed from the sponsor model (gap G-02): derived as FY25 audited less reported Q1–Q3. Stored at [Analyst estimate] status and flagged to CP-1B so quarterly variance work does not over-read the period." },
    "CP-1:Calc Register + KPI Build": { ev: ["E-22", "E-103"], body: "41 KPIs registered with formula, inputs and Python calc references — leverage, coverage, FCF conversion (K-22) and covenant EBITDA (K-09) among them. Every figure consumed downstream resolves to this register, never to ad-hoc math." },
    "CP-1:Definition Conflict Register": { ev: ["E-09", "E-103"], body: "Two conflicts logged, not silently reconciled: (1) the SFA caps cost-saving add-backs at 25% over 24 months while the 2L credit agreement is uncapped — covenant calculations diverge by $14.2M; (2) the sponsor model's EBITDA basis differs from the audited presentation." },
    "CP-1:Gaps + Downstream Readiness": { body: "Coverage gate GREEN — all three statements present at quarterly grain FY23–LTM. G-02 carried as the only open item. All 11 downstream consumers cleared to start." },
    "CP-1A:Operating Model": { ev: ["E-12", "E-31"], body: "Three-segment model: Drivetrain (46% revenue), Fluid Systems (31%), Aftermarket & Services (23% revenue / 44% gross profit). 71% of COGS is indexed pass-through with a 60–90 day lag; aftermarket attaches to a 1.9M-unit installed base renewing at 92%." },
    "CP-1A:Credit Translation": { ev: ["E-12", "E-15"], body: "The installed-base annuity is the core credit support; top-3 OEM concentration (38%) is the principal structural weakness, concentrated in Drivetrain. Both translated into transmission mechanics and handed to CP-2 / CP-2B." },
    "CP-1B:Variance Analysis": { ev: ["E-58"], body: "Q1-26 actuals $108M vs sponsor model $112.7M (−4.2%); shortfall concentrated in Fluid Systems volume (−$3.1M) and cost-out phasing (−$1.6M). Conflict logged to CP-5; the model is demoted to upside case." },
    "CP-1B:Overall Earnings View": { body: "Earnings trajectory intact — +6.2% LTM EBITDA growth, book-to-bill 1.06x, realized price (+180bps) running ahead of input inflation (+140bps). The sponsor model runs hot; CP-1 normalized actuals are the base." },
    "CP-1C:Metric Alignment Register": { ev: ["E-44"], body: "Peer metrics aligned to CP-1 definitions before comparison. The peer EBITDA margin set cites CIM Annex C p.388, which actually contains the auditor consent letter — raised as QA-117 (HIGH). Benchmark conclusions are carried ex-E-44 pending re-anchor." },
    "CP-1C:Transaction Comps": { body: "Only two clean transaction datapoints in-perimeter (Hartwell bolt-on '23 at 6.4x; one sector take-private '24 at 7.8x). Thin set — used directionally for the implied-EV cross-check only and flagged as a limitation." },
    "CP-1C:Overall Peer Benchmarking View": { ev: ["E-71"], body: "Subject screens +61bps wide of the B2 median with top-quartile FCF conversion and above-median margin. Ex-E-44 the cheapness compresses to +20–25bps — still positive carry against fundamentals." },
    "CP-2:Financial Profile & Credit Quality": { body: "9-dimension scorecard: EBITDA quality and leverage score weakest (add-backs 18.2% of adj. EBITDA); FCF conversion and revenue durability strongest. Composite lands mid-B2, consistent with agency ratings." },
    "CP-2B:Downside Pathway Register": { body: "Three pathways, each with an explicit transmission chain. P1 (OEM destocking) is the fastest — Drivetrain volumes −12% over two quarters with absorption deleverage compounding to −18% EBITDA, at 25% probability." },
    "CP-2C:Catalyst Calendar": { body: "Nine catalysts inside 12 months, front-loaded into H2-26 reporting. The Q3-26 compliance certificate is the thesis-defining print — wired to trigger T-1 and a CP-6A re-vote if add-back realization lands under $30M." },
    "CP-2D:Behavior Flag Register": { ev: ["E-91"], body: "Two flags: dividend-recap history at two Fund IV portfolio companies within 24 months of a refinancing window, and RP builder-basket pre-positioning ($240M with no stated use). Fund VI close logged as an offsetting support-capacity INFO flag." },
    "CP-2E:12-Month Liquidity Bridge": { ev: ["E-77"], body: "Bridge nets +$96M over 12 months from $379M beginning accessible liquidity (cash $184M + accessible RCF $195M net of LCs). Largest uses: cash interest $196M, capex $121M, working-capital trough $43M." },
    "CP-2E:Months to Empty Result": { ev: ["E-77"], body: "19.3 months base case; 14.0 under CP-2B pathway P1 with the springing covenant untested (utilization 22% vs 40% trigger). Calculated only because both inputs are source-supported, per module calculation rules." },
    "CP-2F:Hedging Register": { body: "Not producible: the hedging register and swap confirms were not provided (gap G-01). Per prohibited-behavior rules the register is marked [Insufficient Information] rather than assumed. Floating exposure is modeled from SFA margins only and every consumer sees limitation L-04." },
    "CP-2F:+100bps Rate Sensitivity": { body: "+100bps in base rates costs ~$12.1M of FCF (7% of LTM FCF) on the fully-unhedged assumption. The figure is an upper bound — any undisclosed hedges would reduce it. Resolution of G-01 re-rates this table." },
    "CP-3:Relative Value Table": { ev: ["E-71", "E-44"], body: "Subject at +388 vs fair band +325–340 → +48–63bps cheap to model. The band leans on E-44; the ex-E-44 construction (sector beta regression) still shows +20–25bps. Both bands carried until QA-117 resolves." },
    "CP-3B:Recovery Sensitivity Table": { body: "2L recovery spans 21–100% across the 5.0–7.5x multiple / $295–421M EBITDA grid. The cliff sits below 5.5x on stressed EBITDA, where 1L claims consume the estate before the 2L attaches." },
    "CP-3B:Preference Decision Table": { body: "2L TL preferred over the TLB: +210bps of spread pickup for an acceptable recovery delta at the 6.0x stress point. Sub notes rejected on priming exposure and thin covenant protection." },
    "CP-3C:Risk Budget Flags": { body: "The B3-or-below bucket at 91% utilization is the binding flag — max sizing (125bps) requires a same-day headroom re-test. All other budgets (issuer, sector, sponsor, correlation) pass with material headroom." },
    "CP-3D:Legal Capacity for LME": { ev: ["E-63", "E-64"], body: "Uptier path OPEN: $612M day-one incremental capacity, sacred-rights amendment vote at 50.1%, and MFN protection sunsetting June 2027. No J.Crew/Chewy blockers — the capacity is real and is priced via sizing, not exclusion." },
    "CP-3D:Vulnerability Score Table": { body: "4/10 today — no near-term wall, genuine FCF, open market access. Re-rates to 7/10 if P1 stress coincides with the 2029 TLB refinancing approach, when legal capacity meets motive." },
    "CP-4:Aggressiveness Score": { body: "7.2/10 — Aggressive tier vs the 2026 single-B market norm of 6.1. Driven by uncapped credit agreement add-backs, $612M day-one capacity and the 12-month MFN sunset; partially offset by full guarantor coverage and the absence of an unrestricted-sub transfer basket." },
    "CP-4:Red Flags & Monitoring Triggers": { ev: ["E-63", "E-64"], body: "Two red flags wired to standing triggers: any incremental raise above $200M inside the MFN sunset (T-2) and any RP-basket activation (T-4). Both route to a CP-3B re-rank and CP-6E sizing review on trip." },
    "CP-4C:Capacity Register": { ev: ["E-63"], body: "Freebie $150M (grower ≈ 35% × EBITDA) + ratio capacity $310M at 4.68x secured leverage + reclassification headroom $155M = $612M day-one, incurrable senior or pari passu to the 2L TL." },
    "CP-4C:Add-Back Inflation Analysis": { ev: ["E-09", "E-87"], body: "Add-backs run at 18.2% of adj. EBITDA and feed every grower basket — capacity inflates mechanically with each 'one-time' charge. CP-1's recurrence finding (charges in 3 of the last 4 years) makes the inflation structural, not episodic." },
    "CP-4C:Nearest Pressure Point": { ev: ["E-64"], body: "The MFN sunset, June 2027. After it, a priming or pari incremental raise carries no yield protection for 2L lenders — the single most consequential date in the document set." },
    "CP-5:Citation & Evidence Audit": { ev: ["E-44"], body: "All 21 modules audited; 1,142 citations resolved against the source vault. One HIGH defect: CP-1C's E-44 anchors to the wrong page of the conformed CIM (QA-117). No fabricated or orphaned citations found." },
    "CP-5:Consolidated Issue Log": { body: "One HIGH open (QA-117), two LOW resolved in-run (CP-2C probability labeling; CP-3 rounding). The HIGH finding blocks committee-pack assembly under clearance policy — no override path short of remediation." },
    "CP-5:Clearance Decision": { body: "CONDITIONAL — CP-RENDER and CP-EXTRACT held until remediation R-1 lands (re-anchor E-44, re-run CP-1C alignment, refresh CP-3 and the CP-6A weighting row). Math, legal, market and consistency audits are clean." },
    "CP-5B:Weak-Lineage Flags": { ev: ["E-44"], body: "Driver #5's chain terminates at a mismatched anchor (E-44) and is flagged weak; remediation is owned by CP-5 R-1. The remaining four drivers trace to grade-A sources within three hops." },
    "CP-5B:Auditability Assessment": { body: "STRONG — every figure in the committee pack resolves to a registered evidence ID and a calc-register reference. Reconstruction time for any material number is under two minutes from the master index." },
    "CP-6A:Chair Evidence Weighting": { body: "Five contested claims scored bull/bear across nine evidence dimensions. Bear prevails on EBITDA quality (65/35) and documentation (75/25); bull prevails on aftermarket stickiness (80/20); RV is split pending QA-117." },
    "CP-6A:Action Bias Determination": { body: "CONSTRUCTIVE — add on weakness. The bear case is real but priced at +388: haircut the base case by $35M of EBITDA, size below max, and let carry plus deleveraging do the work." },
    "CP-6A:Single Greatest Uncertainty": { ev: ["E-103"], body: "Add-back realization. If the Q3-26 certificate shows under $30M realized, base-case deleveraging fails and the position reverts to a 6.9x credit bought at a 5.7x price — trigger T-1 forces the re-vote." },
    "CP-6E:Final Sizing Posture": { body: "75bps initial at +388 or wider; path to the 125bps max is gated on trigger T-1 (Q3-26 add-back certificate) and a same-day B3-bucket headroom check. Add-on-weakness, with a standing limit order at +400bps." },
    "CP-6E:Exact Portfolio Constraint": { body: "The binding constraint is the B3-or-below quality bucket at 91% utilization — not issuer, sector, sponsor or correlation limits. Any add must re-test the bucket on trade date; this is encoded in the sizing decision." },
  };

const EXT: Record<string, StepNote> = {
    /* ---- CP-0 · Document Intake ---- */
    "CP-0:File Classification": { body: "All 14 deal-room files typed against the document taxonomy on first pass — CIM, SFA, 2L credit agreement, audited financials, compliance certificate, lender presentation and sponsor model extract. No unclassifiable or corrupted files." },
    "CP-0:Entity Identification": { body: "Issuer perimeter resolved to Atlas Forge Intermediate Holdings, Inc., with Atlas Forge Industrials as the operating group. Guarantor set and the Kestrel ownership chain registered so every downstream module cites one canonical entity key." },
    "CP-0:Document Mapping": { body: "Each document mapped to its consuming modules: CIM and audits to the L1 financial modules, SFA and credit agreement to CP-4/4C, the compliance certificate to covenant calculations, the lender presentation and sponsor model (MNPI-handled) to CP-1B and CP-2D." },
    "CP-0:Quality Assignment": { body: "Grades assigned A–C: executed legal documents and audited financials grade A; lender presentation grade B (sponsor-prepared, MNPI); sponsor model extract grade C — unaudited, admissible only with [Analyst estimate] labeling." },
    "CP-0:Content-Module Mapping": { body: "Section-level routing complete — CIM Annex C to CP-1C, credit agreement §4.07/§4.09 to CP-4C, MD&A liquidity disclosure to CP-2E. 312 content anchors registered to the master index." },
    "CP-0:Conflict Logging": { body: "Zero unresolved conflicts at intake: CIM summary financials tie to the audited statements within tolerance, and the certificate's covenant EBITDA reconciles to the SFA definition." },
    "CP-0:File Quality Risk": { body: "Aggregate file-quality risk LOW: every thesis-critical claim is coverable from grade-A sources. Grade-C material (sponsor model) is confined to upside-case and variance work." },
    "CP-0:Master Index Update": { body: "Master index rebuilt: 14 documents, 312 content anchors, 2 open gaps — the single addressable map that every E-xx citation resolves against." },
    "CP-0:Export Assembly": { body: "Intake export assembled and handed to CP-X: document map, quality grades, gap/conflict logs and the 0.91 readiness score in one routable package." },

    /* ---- CP-X · Orchestration ---- */
    "CP-X:Module Execution Sequence": { body: "21 modules sequenced into 8 dependency waves: financial spreading before synthesis, legal and RV before the debate layer, governance last at the J1 join. No circular dependencies detected." },
    "CP-X:Module Readiness Register": { body: "All 21 modules report GREEN inputs at route time. CP-2F enters in degraded mode (L-04) but remains routable; no module is blocked on missing sources." },
    "CP-X:One-Owner-Per-Object Validation": { body: "Every output object has exactly one producing module — 0 collisions. Capacity math is owned by CP-4C, recovery math by CP-3B; consumers reference, never recompute." },
    "CP-X:Source-to-Module Routing Map": { body: "Routing locked: each document section routes to its owning module with MNPI handling preserved (D-06 / D-07 restricted to walled consumers). 100% of grade-A anchors claimed." },

    /* ---- CP-1 · Financial Spreading ---- */
    "CP-1:Source Register (file gate)": { body: "File gate PASS — audited FY23–FY25 statements, Q1-26 interims and the compliance certificate admitted as the spreading basis. Sponsor model admitted at grade C for derived-period work only." },
    "CP-1:Entity / Period Key": { body: "Single entity key (Atlas Forge Intermediate Holdings) and a 12-period quarterly grid FY23–LTM Q1-26 fixed before any spreading. All downstream KPIs cite this key." },
    "CP-1:Income Statement Coverage": { body: "Income statement covered at quarterly grain for all 12 periods — revenue through adjusted EBITDA with the add-back bridge preserved as separate lines, never netted away." },
    "CP-1:Cash Flow Statement Coverage": { ev: ["E-22"], body: "Cash flow coverage complete: operating cash, capex and free cash flow reconciled to the audited statements for every period. No plugged figures." },
    "CP-1:Balance Sheet Coverage": { body: "Balance sheet covered for all periods; the net debt build ($2,391M LTM) reconciles to the facility-level debt schedule consumed by CP-3B's capital structure dashboard." },
    "CP-1:Normalized Financials Table": { ev: ["E-103"], body: "The published normalized table: revenue $2,801M LTM, adj. EBITDA $421M at 15.0% margin, FCF $172M, net leverage 5.68x — the canonical figures every downstream module consumes." },
    "CP-1:Evidence→Risk→Credit Narrative": { ev: ["E-09"], body: "Spreading translated into credit language: real FCF generation and stable margins support the credit; the $76.6M add-back wedge (18.2% of adj. EBITDA) is the headline quality risk handed to CP-2 and CP-4C." },

    /* ---- CP-1A · Company Profile ---- */
    "CP-1A:Source Basis Establishment": { body: "Descriptive basis fixed to the CIM business section and audited segment notes. The lender presentation is used for color only, with every claim cross-checked to a grade-A anchor." },
    "CP-1A:Source Classification": { body: "Sources split factual vs promotional: CIM risk factors and audit notes drive the record; sponsor-authored growth claims are quarantined under [Sponsor view] labeling." },
    "CP-1A:Transaction Summary": { body: "Subject transaction: $900M 2L TL '31 at S+425, refinancing the 2L bridge plus general corporate purposes — the fifth capital-structure event since the 2021 Kestrel LBO at 7.9x." },
    "CP-1A:Business Description": { body: "Engineered metal components for industrial OEMs — 14 plants across US / EU / MX, a 1.9M-unit installed base, and #1 or #2 share in 7 of 9 core product lines." },
    "CP-1A:Ownership Register": { body: "Kestrel Capital Fund V controls 68.4%; management rollover 9.2%; co-invest vehicles 22.4%. Board is 1-of-7 independent — registered for CP-2D's governance work." },
    "CP-1A:History / Timeline": { body: "Timeline registered: 2021 LBO ($2,150M EV, 7.9x) → 2023 Hartwell bolt-on (6.4x) → 2024 repricing + $250M incremental TLB → 2026 2L TL refinance. The pattern: steady re-leveraging events." },
    "CP-1A:Gaps Ledger": { body: "No descriptive gaps — org chart, segment detail and plant footprint all source-supported. Carve-out detail on the MX facility noted as thin but non-material." },
    "CP-1A:Module Summary": { body: "A scaled, defensible industrial franchise with an annuity-grade aftermarket attached to a concentrated OEM book — descriptive facts handed clean to CP-2." },

    /* ---- CP-1B · Earnings Monitor ---- */
    "CP-1B:File Gate & Source Validation": { body: "Gate PASS on Q1-26 interims and the compliance certificate; sponsor model admitted as a comparison basis only (grade C). Q4-25 derived-period caveat inherited from CP-1." },
    "CP-1B:Issuer / Period Scope": { body: "Scope locked to the last four quarters against CP-1's normalized history — same entity key, same definitions, no restated comparatives." },
    "CP-1B:Definition Inheritance": { body: "All KPI definitions inherited from the CP-1 calc register unchanged — margins, leverage and FCF conversion computed identically, so variances are real rather than definitional." },
    "CP-1B:Summary Top Sheet": { body: "Top sheet: Q1-26 revenue $715M (+3.9% y/y), adj. EBITDA $108M at 15.1% margin, book-to-bill 1.06x — trajectory intact against both prior year and sequential quarters." },
    "CP-1B:Financial Performance Table": { body: "Quarterly performance published Q2-25 through Q1-26: revenue compounding ~1.3% sequentially with margin pinned in a 14.9–15.1% band." },
    "CP-1B:KPI Dashboard": { body: "41 KPIs refreshed. Aftermarket mix grinding up (22.4% → 23.4% over four quarters) is the single most thesis-supportive operational trend in the dashboard." },
    "CP-1B:Corporate Actions": { body: "Two actions in window: the May-26 2L TL issuance itself and a Hartwell earnout settlement ($24M committed) — both reflected in CP-2E's liquidity bridge." },
    "CP-1B:Comparative Evaluation": { body: "Against the CP-1C peer set, the Q1 print was middle-of-pack on growth but top-quartile on margin stability. No peer-relative deterioration detected." },
    "CP-1B:Conflict Log": { ev: ["E-58"], body: "One conflict: sponsor-model FY26E EBITDA phasing vs actuals (−4.2% in Q1). Logged to CP-5; the model is demoted to upside case rather than silently averaged in." },
    "CP-1B:Monitoring Assessment": { body: "Monitoring wired to the Q2-26 print (Jul 28): add-back realization, Fluid Systems volume recovery and book-to-bill are the three watch items handed to CP-2C." },
    "CP-1B:Gaps & Limitations Ledger": { body: "The Q4-25 derived-period caveat (G-02) is the only open limitation; quarterly comparisons crossing that period are flagged in-table." },

    /* ---- CP-1C · Peer Benchmarking ---- */
    "CP-1C:Peer Discovery Gate": { body: "Peer discovery admitted 11 candidates from sector screens; 4 dropped for business-mix mismatch, leaving a 7-name universe of single-B engineered-components credits." },
    "CP-1C:Peer Data Gate": { body: "Peer financials sourced from public filings and the CIM industry annex. Data sufficiency PASS for 7 of 7 on the core metric set (margin, leverage, FCF, spread)." },
    "CP-1C:Peer Universe Register": { body: "Universe registered: Forgeline, Karst, Veldt, Ironvale, Cascadia, Tarn + subject — comparable scale ($1.5–3.5B revenue), B1–B3 rating band, same OEM / aftermarket structure." },
    "CP-1C:Operating Benchmark": { body: "Subject's 15.0% EBITDA margin ranks 64th percentile; revenue growth in line with peer median; aftermarket mix second-highest in the set behind Veldt." },
    "CP-1C:Cash Flow & Capital Intensity": { ev: ["E-22"], body: "Capex at 4.3% of revenue is the second-lightest in the universe; 41% FCF conversion is top-quartile — the clearest fundamental edge over the peer set." },
    "CP-1C:Credit Metric Benchmark": { body: "Published 4C table: subject at 5.7x / 15.0% / 41% / +388 vs the B2 median's 5.5x / 13.9% / 31% / +327 — modestly more levered, meaningfully better converting." },
    "CP-1C:Summary Statistics": { body: "Medians computed ex-Tarn (distressed outlier): net leverage 5.5x, margin 13.9%, DM +327. The subject sits +61bps wide of median on better fundamentals." },
    "CP-1C:Outlier Register": { body: "Tarn Engineered (B3 / CCC+, +577bps) excluded from medians as a distressed outlier; retained in the table for context. No other exclusions." },
    "CP-1C:Public Trading Comps": { body: "Listed comps (3 names) trade at 8.9–10.4x EV/EBITDA; the midpoint applied to the subject implies comfortable coverage through the 2L attachment point." },
    "CP-1C:Implied EV": { body: "Implied-EV cross-check: 9.5x midpoint × $421M ≈ $4.0B vs $3.3B total debt — an equity cushion exists at trading multiples, eroding only below ~7.9x." },
    "CP-1C:Peer Interpretation & Credit Translation": { body: "Translation: the market prices ATLF as an average B2 while fundamentals (FCF conversion, aftermarket mix) screen better-than-cohort — the basis for the RV cheap reading, carried ex-E-44." },
    "CP-1C:Gaps & Limitations Ledger": { body: "Two limitations: the E-44 anchor mismatch (QA-117) and the thin transaction-comp set. Both carried visibly on the conclusions rather than papered over." },

    /* ---- CP-2 · Credit Synthesis ---- */
    "CP-2:Source Gate & Readiness": { body: "Gate PASS — consumes CP-1 / 1A / 1B / 1C published outputs only; no raw-document re-extraction. All four feeders GREEN at start." },
    "CP-2:Company Description": { body: "Descriptive frame inherited from CP-1A and condensed for committee use: scaled engineered-components platform, three segments, aftermarket annuity attached to a 1.9M-unit installed base." },
    "CP-2:Ownership & Group Structure": { body: "Kestrel control (68.4%) and the covenant-group perimeter confirmed; no orphaned value sits outside the restricted group — relevant given CP-4's transfer-basket findings." },
    "CP-2:Revenue Drivers & Pricing Power": { ev: ["E-31", "E-15"], body: "Pricing power MODERATE: indexed pass-through on 71% of OEM COGS protects gross margin mechanically, but top-3 concentration caps realized pricing on the Drivetrain book." },
    "CP-2:Cost Structure & Margin Resilience": { body: "Margin resilience tested across FY22–LTM: a 14.9–15.1% band held through an input-cost spike cycle — the 60–90 day lag creates quarter noise, not structural erosion." },
    "CP-2:Capital Intensity & FCF Conversion": { ev: ["E-22"], body: "Capex 4.3% of revenue with maintenance estimated at 2.9%; 41% FCF conversion is genuine and the strongest quantitative support in the credit." },
    "CP-2:Porter Five Forces": { body: "Five-forces read: supplier power LOW (indexed inputs), buyer power HIGH (OEM concentration), entry barriers HIGH (qualified-vendor lock-in), substitutes LOW, rivalry MODERATE." },
    "CP-2:PEST Analysis": { body: "PEST: the rate environment is the live macro channel (61% floating, modeled unhedged); reshoring policy is a mild tailwind for the US footprint; no material regulatory or social exposure." },
    "CP-2:SWOT Analysis": { body: "SWOT condensed — strengths: aftermarket annuity, FCF; weaknesses: add-back quality, OEM concentration; opportunities: Fund VI-backed bolt-ons; threats: a destocking cycle meeting the MFN sunset." },
    "CP-2:Key Strengths & Weaknesses": { body: "Net assessment: two durable strengths (annuity economics, cash conversion) against two structural weaknesses (EBITDA presentation, customer concentration) — neither side dominant." },
    "CP-2:Outlook, Tailwinds & Headwinds": { body: "Outlook STABLE: the order book supports low-single-digit growth. Headwinds are the Meridian repricing (Q2-27) and cost-out phasing risk into the FY26 add-back test." },
    "CP-2:Qualitative Downside Scenario": { body: "Qualitative downside: an OEM destocking cycle compresses Drivetrain while 'one-time' charges recur — quality risk and volume risk arriving together. Quantified by CP-2B as pathway P1." },
    "CP-2:Materiality Filter": { body: "23 candidate factors filtered to 6 material ones; immaterial color (FX translation, single-plant items) dropped so the issuer matrix stays decision-grade." },
    "CP-2:Issuer Matrix": { body: "Six material factors scored with trend and weight — published as the issuer matrix consumed directly by CP-6A's pre-debate thesis map." },
    "CP-2:Monitoring Triggers": { body: "Four standing triggers set: add-back realization (T-1), incremental raise inside the MFN window (T-2), Meridian repricing terms (T-3), RP-basket activation (T-4)." },
    "CP-2:Overall Credit View": { ev: ["E-09"], body: "B2 / STABLE affirmed: deleveraging to ~4.9x by FY27 is credible on realized add-backs alone. The binding risks are documentation-enabled releveraging and the Meridian contract cycle." },

    /* ---- CP-2B · Downside Pathways ---- */
    "CP-2B:Source Gate & Baseline": { body: "Gate PASS off CP-1 normalized actuals ($421M LTM adj. EBITDA) as the stress baseline — the sponsor model is explicitly excluded from stress arithmetic." },
    "CP-2B:Business Model Snapshot": { body: "Snapshot fixes the stress-relevant mechanics: 46% Drivetrain exposure, operating leverage across 14 plants, the pass-through lag, and the aftermarket buffer at 44% of gross profit." },
    "CP-2B:Fragility Map": { body: "Four fragilities mapped (F-1 absorption deleverage, F-2 OEM concentration, F-3 pass-through lag, F-4 covenant-capacity interaction) — each tied to an observable early indicator." },
    "CP-2B:Stress Transmission Table": { body: "Transmission quantified: a 10% Drivetrain volume decline translates to ~−14% EBITDA after absorption effects; aftermarket dampens but does not offset within two quarters." },
    "CP-2B:Downside Sensitivity Matrix": { body: "Sensitivity grid spans volume −5% to −15% against cost-out delivery 0–100%: EBITDA outcomes of $345–415M, with leverage holding under 7.0x in all but the corner case." },
    "CP-2B:Monitoring Sensitivity Flags": { body: "Three early-warning flags wired: OEM order intake (monthly), Drivetrain book-to-bill below 0.95x, and distributor inventory above 11 weeks." },
    "CP-2B:Cross-Module Handoff Register": { body: "Handoffs registered: P1 feeds CP-3D's stress-coincidence scenario, the sensitivity grid feeds CP-3B's stressed-EBITDA axis, and all pathway probabilities feed CP-6A." },
    "CP-2B:Gaps Ledger": { body: "No module-specific gaps; inherits the G-02 derived-period caveat on quarterly granularity only." },
    "CP-2B:Overall Downside Pathway View": { ev: ["E-77", "E-64"], body: "No pathway breaks liquidity — P1 (worst) leaves 14 months-to-empty. The structural danger is sequencing: P1 arriving inside the open MFN window invites a priming raise at the cycle bottom." },

    /* ---- CP-2C · Catalyst Calendar ---- */
    "CP-2C:Source Gate & Calendar Scope": { body: "Gate PASS; calendar scoped to 12 months forward with issuer, sponsor, sector and documentation event classes all in perimeter." },
    "CP-2C:Event Source Register": { body: "Events sourced from filing calendars, facility documents (compliance dates), Kestrel fund communications and sector OEM reporting schedules — each event carries a source anchor." },
    "CP-2C:Event Risk Register": { body: "Nine events registered with direction and mechanism — six issuer-specific, two sponsor-driven, one sector-wide (the OEM destocking data cycle)." },
    "CP-2C:Probability-Impact Matrix": { body: "The matrix places the Q3-26 compliance certificate and the Meridian repricing in the high-impact / high-probability quadrant; Kestrel exit commentary is high-impact / low-probability." },
    "CP-2C:Monitoring Priority Table": { body: "Priorities ranked: certificate prints first, OEM order data second, RP-basket activity third — mapped onto the CP-MON monitoring cadence." },
    "CP-2C:Watchlist Handoff Register": { body: "Three handoffs: T-1 (certificate) to a CP-6A re-vote, Meridian terms to a CP-2B P1 refresh, and Kestrel exit signals to a CP-2D posture review." },
    "CP-2C:Gaps & Limitations Ledger": { body: "Probabilities stated without basis were re-labeled [Analyst estimate] after QA-121 — resolved in-run; no open items." },
    "CP-2C:Overall Catalyst View": { body: "Event risk front-loads into H2-26 reporting. The calendar is wired so each catalyst routes to a named module action rather than passive watching." },

    /* ---- CP-2D · Sponsor & Governance ---- */
    "CP-2D:Source Register & Readiness": { body: "Gate PASS off the CP-1A ownership register, the lender presentation (MNPI-handled) and Kestrel fund communications; READY." },
    "CP-2D:Ownership & Control Register": { body: "Control confirmed: Kestrel 68.4% with drag rights and board control (6 of 7 seats); management 9.2% rolled — alignment is sponsor-dominated." },
    "CP-2D:Governance Register": { body: "Governance is institutional but sponsor-controlled: 1 of 7 directors independent, the audit committee chaired by the independent, and a monthly lender-reporting cadence." },
    "CP-2D:Capital Allocation Risk Table": { body: "Allocation history scored: bolt-on M&A is disciplined (6.4x paid vs the 7.9x platform), but two prior Kestrel-portfolio dividend recaps inside 24 months of refi windows set the pattern risk." },
    "CP-2D:Acquisition Appetite Table": { body: "Appetite HIGH: fresh Fund VI capital, a stated industrials focus and an existing platform — bolt-ons likely, fundable inside existing baskets per CP-4C capacity." },
    "CP-2D:Disclosure Quality Log": { body: "Disclosure grade B+: monthly lender packages, quarterly calls and covenant detail above market norm; deductions for sponsor-model optimism and selective KPI presentation." },
    "CP-2D:Creditor Alignment Table": { body: "Alignment MODERATE: sponsor incentives favor enterprise growth near-term, but the RP pre-positioning and recap history signal extraction risk in the 2027–28 window." },
    "CP-2D:Sponsor Risk Assessment": { body: "Composite MODERATE-HIGH: a competent operator with an extractive financial policy. The risk is behavioral and documentation-enabled, not operational." },
    "CP-2D:Cross-Module Handoff Register": { body: "Handoffs: RP-basket activation wired to trigger T-4; Fund VI support capacity logged for CP-3D's sponsor-willingness table; the recap pattern fed to the CP-6A bear file." },
    "CP-2D:Gaps Ledger": { body: "No gaps. LP-letter detail on Fund VI deployment pace noted as desirable but non-blocking." },
    "CP-2D:Overall Governance View": { ev: ["E-91"], body: "Kestrel is a competent operator with an extractive financial-policy record; institutional-grade disclosure partially offsets. Posture: treat the RP basket as the tell — any activation is a posture-changing event." },

    /* ---- CP-2E · Liquidity ---- */
    "CP-2E:Source Register & Module Status": { ev: ["E-77"], body: "Gate PASS off the audited liquidity disclosure, facility schedules and the CP-1 cash-flow build; READY with no limitations." },
    "CP-2E:Beginning Liquidity Register": { body: "Beginning accessible liquidity $379M: cash $184M plus $195M undrawn RCF net of $12.4M of LCs — accessibility verified against facility conditions, not just stated availability." },
    "CP-2E:Mandatory Cash Uses Register": { body: "Mandatory uses over the next 12 months: cash interest $196M, TLB amortization $18M, Hartwell earnout $24M — no maturities and no mandatory prepayment events." },
    "CP-2E:WC & Capex Pressure Table": { body: "Seasonal working-capital trough of $43M (Q3) and capex of $121M registered; both covered by operating cash without RCF reliance in the base case." },
    "CP-2E:Mitigants & Constraints Table": { body: "Mitigants: capex deferability (~$25M) and a receivables-facility option. Constraints: the springing covenant above 40% RCF utilization and the LC carve-out." },
    "CP-2E:Liquidity Risk Level + Narrative": { body: "Risk level ADEQUATE — strong headline liquidity with the springing covenant comfortably untested. The only path to pressure runs through P1-scale EBITDA stress." },
    "CP-2E:Gaps Ledger": { body: "No gaps. Intercompany cash-pooling detail at the MX subsidiary noted as a minor opacity, non-material to the bridge." },
    "CP-2E:Overall Liquidity View": { ev: ["E-77"], body: "Liquidity is a strength: 19.3 months-to-empty base, 14.0 under P1 stress, and nothing due inside 24 months. The springing covenant tests only above 40% utilization (currently 22%)." },

    /* ---- CP-2F · Macro & Hedging ---- */
    "CP-2F:Source Register & Module Status": { body: "READY WITH LIMITATIONS — the hedging register is absent (gap G-01); the module runs in degraded mode with every output stamped L-04." },
    "CP-2F:Debt & Rate Exposure Register": { body: "Exposure register: RCF $120M, TLB $1,850M and the 2L TL $900M floating (SOFR+350/375/425); Subs $400M fixed — an 88% floating share before any undisclosed hedges." },
    "CP-2F:Unhedged Floating Exposure": { body: "Floating exposure modeled from SFA margins only and treated as fully unhedged per prohibited-assumption rules — an explicit upper bound, not an estimate." },
    "CP-2F:FX Exposure Register": { body: "FX LOW: 84% of revenue and 81% of costs in USD; EUR plant costs naturally hedged by EU revenue; translation-only exposure on the MX facility." },
    "CP-2F:Commodity & Inflation Table": { ev: ["E-31"], body: "Steel and alloy inputs (71% of COGS) pass through with a 60–90 day lag — inflation is a timing exposure, not a level exposure." },
    "CP-2F:Macro Sensitivity Summary": { body: "The dominant channel is rates: +100bps ≈ −$12.1M of FCF on the unhedged bound. Commodity and FX channels are second-order." },
    "CP-2F:Gaps Ledger": { body: "G-01 open — swap confirms re-requested Jun 04. Resolution would re-rate the rate-sensitivity table and lift limitation L-04 from all consumers." },
    "CP-2F:Overall Macro / Hedging View": { body: "Macro view carried with the L-04 caveat: rate sensitivity is real but bounded above; the credit is structurally insulated on commodities and FX." },

    /* ---- CP-3 · Relative Value ---- */
    "CP-3:Source Register + Execution Mode": { ev: ["E-71"], body: "Gate PASS; executed in full-stack mode consuming CP-1C benchmarks, the CP-2 credit view and live desk marks." },
    "CP-3:Fundamental Credit Summary": { body: "Fundamental summary lands mid-B2 with positive trajectory: real FCF and a credible deleveraging path, with quality and concentration as the standing deductions." },
    "CP-3:Issuer / Security Scorecard": { body: "Scorecard 71/100: cash flow 17/20, business durability 15/20, leverage 12/20, documentation 9/20 — documentation is the scored weak point, consistent with CP-4." },
    "CP-3:Override Review": { body: "No analyst overrides applied — the scorecard output is carried as computed and the override register is empty." },
    "CP-3:Fundamental Value Matrix": { body: "The matrix crosses fundamentals against spread: the subject plots in the cheap / improving quadrant. Only Cascadia plots cheaper, on an unsecured-recovery adjustment the IC discounts." },
    "CP-3:Final Ranking": { body: "Final rank 2 of 7 on the value matrix. The rank is robust to the E-44 question — dropping the contested margin set moves the subject to 3 of 7, still actionable." },
    "CP-3:Security Selection Conclusions": { body: "Within the structure, the 2L TL is the expression: +210bps of pickup over the TLB for an acceptable recovery delta (per CP-3B); subs rejected on priming exposure." },
    "CP-3:Monitoring Triggers": { body: "RV triggers: exit if spread tightens through +300 (thesis complete); re-rank on any peer-set rating migration; refresh marks weekly." },
    "CP-3:Gaps Ledger": { body: "The E-44 dependency is carried as the single limitation; both fair-value bands (with and ex-E-44) are published side by side." },
    "CP-3:Final Credit / RV View": { ev: ["E-71"], body: "Conviction is carry plus deleveraging, not convergence: hold-to-maturity math clears the hurdle at +388 with zero spread tightening assumed." },

    /* ---- CP-3B · Instrument Selection ---- */
    "CP-3B:Instrument Data Gate": { body: "Gate PASS — facility-level terms, pricing and ranking for all five instruments verified against executed documents; claims totals tie to CP-1 net debt." },
    "CP-3B:Capital Structure Dashboard": { body: "Dashboard published: $3,270M of total debt — RCF / TLB (1L $1,970M), 2L TL $900M, Subs $400M — 5.7x through the subject tranche, 6.6x total." },
    "CP-3B:Instrument Matrix": { body: "The matrix scores each tranche on price, ranking, covenant protection and liquidity: the 2L TL carries the best spread-per-risk-unit, the TLB the best downside, the subs the worst of both." },
    "CP-3B:Structural Positioning Log": { body: "Positioning: the 2L TL sits behind $1,970M of 1L claims with full guarantor coverage and second-lien collateral — and structurally ahead of a $400M sub-notes cushion." },
    "CP-3B:Legal / Covenant / LME Overlay": { ev: ["E-63", "E-64"], body: "CP-4C overlay applied: $612M of incremental capacity can prime the 2L and MFN protection lasts only 12 months — LME risk is priced into the preference decision rather than ignored." },
    "CP-3B:Compensation Cross-Check": { body: "Cross-check PASS: at +388 the 2L compensates its modeled loss-given-default with ~140bps of excess spread under base-distress probability weights." },
    "CP-3B:Ranking & Trade-Off Summary": { body: "Trade-off summary: 2L TL > TLB > Subs. The 2L's recovery cliff below 5.5x stressed is the accepted risk, paid for by +210bps of spread." },
    "CP-3B:Monitoring Triggers": { body: "Three triggers: any 1L incremental raise (re-runs the waterfall), a discounted sub-notes repurchase below 85 (signals LME posture), and TLB price decoupling from the 2L TL." },
    "CP-3B:Gaps Ledger": { body: "No instrument-level gaps. Lease and pension claims modeled from audit notes at $61M combined — immaterial to attachment points." },
    "CP-3B:Overall Instrument Preference View": { body: "2L TL preferred — the only tranche where spread, structural position and covenant protection are jointly acceptable. The preference stands under both fair-value bands." },

    /* ---- CP-3C · Portfolio Fit ---- */
    "CP-3C:Portfolio Input Gate": { body: "Gate PASS — the live portfolio snapshot (Jun 8), limit framework v4.1 and the proposed 75 / 125bps sizing range loaded." },
    "CP-3C:Portfolio Fit Register": { body: "Fit register PASS on all hard limits at initial size: issuer 75bps of a 150bps cap, sector 6.1% of 8.0%, sponsor aggregate 2.2% of 4.0%." },
    "CP-3C:Position Sizing Posture Table": { body: "The posture table supports staged entry: 75bps initial preserves headroom in every budget; 125bps max binds only the B3-or-below bucket." },
    "CP-3C:Concentration & Correlation Register": { body: "The auto / industrial correlation cluster lands at 14.0% of the 16% limit post-add. Pairwise overlap with SXAA is the watched relationship — no concurrent adds ruled." },
    "CP-3C:Liquidity & Implementation": { ev: ["E-71"], body: "Implementation feasible: $4.2M average LoanX clip and two-way desk markets support building 75bps inside ~2 weeks without moving the price." },
    "CP-3C:Downside Budget & Recovery Sensitivity": { body: "At the 21% severe-stress recovery (CP-3B), a max position consumes 9bps of the quarterly downside budget — within the 15bps single-name allowance." },
    "CP-3C:Monitoring / Add-Trim Triggers": { body: "Add / trim wiring mirrors CP-6E: add on a T-1 pass plus bucket headroom; trim on RP activation, a re-rank below 4 of 7, or a cluster breach above 15%." },
    "CP-3C:Gaps Ledger": { body: "No gaps. Portfolio snapshot staleness (T+1) noted as a standard operating limitation; re-tested on trade date by rule." },
    "CP-3C:Overall Portfolio Fit View": { body: "Fit PASS with one watch item: the B3-or-below bucket at 91% utilization is the live constraint, and it is encoded directly into the CP-6E sizing decision." },

    /* ---- CP-3D · Refinancing & LME ---- */
    "CP-3D:Source Register & Module Status": { body: "Gate PASS off facility schedules, CP-2E liquidity outputs and the CP-4C capacity registers; READY." },
    "CP-3D:Maturity Wall Register": { body: "Wall registered: 2027 RCF expiry $250M, 2029 TLB $1,850M, 2031 2L TL $900M, 2032 Subs $400M — nothing due inside 24 months." },
    "CP-3D:Liquidity / Market Access Table": { body: "Market access OPEN: the May-26 2L TL priced inside talk and the TLB trades near par — both primary and secondary channels are available today." },
    "CP-3D:Sponsor Willingness Table": { ev: ["E-91"], body: "Willingness MODERATE-HIGH: Fund VI capacity ($4.2B) supports the platform, but Kestrel's recap record means support is conditional on equity-value preservation, not creditor protection." },
    "CP-3D:Refinancing Path Table": { body: "Paths assessed per instrument: the RCF extends H2-26 at +25–50bps; the TLB is refinanceable at ~SOFR+400; the subs are a discounted-repurchase candidate below 85." },
    "CP-3D:Creditor Class Exposure Table": { body: "Class exposure: 2L holders are the natural LME-target class given priming capacity; the TLB is protected by 1L status; the subs are structurally first-loss." },
    "CP-3D:Monitoring Triggers": { body: "Triggers: TLB price below 97 (refi-risk tell), RCF extension terms, and any amendment solicitation — each routes to a vulnerability re-score." },
    "CP-3D:Scenario Map (base / stress / LME)": { ev: ["E-63"], body: "Three scenarios mapped: base (refi on schedule), stress (P1 coinciding with the 2029 approach → 7/10 vulnerability), and LME (an uptier via §4.09 capacity after the MFN sunset)." },
    "CP-3D:Gaps Ledger": { body: "No gaps. Private-side amendment history unavailable but non-blocking for the vulnerability score." },
    "CP-3D:Overall Refinancing / LME View": { ev: ["E-64"], body: "4/10 today — capacity-driven, not distress-driven: the documents allow an uptier the fundamentals don't yet motivate. The window to watch is 2028–29, when the TLB approach meets open capacity." },

    /* ---- CP-4 · Legal & Covenants ---- */
    "CP-4:Source Gate + Module Status": { body: "Gate PASS — the executed SFA, 2L credit agreement and intercreditor admitted as controlling. CIM covenant summaries are used for navigation only, never as authority." },
    "CP-4:Controlling Document Register": { body: "Controlling register fixed: the executed credit agreement governs the 2L TL, the SFA governs bank debt. Where summaries conflict with executed text, executed text controls — two instances found." },
    "CP-4:Covenant Feature Register": { body: "41 provisions registered across incurrence, restricted payments, liens, transfers, reporting and events of default — each with a clause cite, feature classification and market-norm comparison." },
    "CP-4:EBITDA, Definitions & Ratio Mechanics": { ev: ["E-09", "E-103"], body: "Definitional mechanics are the document's core aggression: uncapped credit agreement add-backs vs the SFA's 25% / 24-month cap — a $14.2M covenant-EBITDA divergence that inflates every grower basket." },
    "CP-4:Debt Incurrence, Incremental & MFN": { ev: ["E-63", "E-64"], body: "The incurrence stack permits $612M day-one (freebie + ratio + reclassification). MFN at 50bps protects pari raises only — and sunsets in June 2027." },
    "CP-4:Leakage, RP, Investments & Transfers": { body: "RP capacity of $240M builder plus starter baskets is usable today. Investment baskets permit unrestricted-sub designation, but no Chewy-style automatic guarantee release was found." },
    "CP-4:Collateral, Guarantees & Subordination": { body: "Full guarantor coverage (87% of EBITDA) with second-lien collateral on substantially all assets; no material non-guarantor pockets — the structural floor of the credit." },
    "CP-4:EoD, Remedies & Amendment Risk": { body: "Sacred rights are limited to money terms, with a 50.1% amendment threshold for everything else — uptier-enabling architecture, standard for the vintage but live given the capacity." },
    "CP-4:PD vs LGD / Recovery Translation": { body: "Translation: this document set shifts risk from PD to LGD — default is not nearer, but the creditor's position at default is erodible via priming and leakage." },
    "CP-4:Market Norm Comparison": { body: "Versus the 2026 single-B norm set: 7.2 vs 6.1 — top-quartile aggressive on definitions and capacity, market-standard on collateral and reporting." },
    "CP-4:Gaps Ledger": { body: "No documentation gaps. The intercreditor's 120-day standstill registered for CP-3B's recovery-timing assumptions." },
    "CP-4:Overall Legal Credit View": { body: "An aggressive but not pathological document set: capacity and definitional looseness are the risks; full collateral / guarantee coverage and the absence of J.Crew / Chewy paths are the protections." },

    /* ---- CP-4C · Covenant Capacity ---- */
    "CP-4C:Source Gate + Module Status": { ev: ["E-103"], body: "Gate PASS — runs off CP-4's covenant register plus the Q1-26 compliance certificate for live ratio inputs; READY." },
    "CP-4C:Controlling Capacity Source Map": { body: "Each capacity figure mapped to its controlling clause: incremental to credit agreement §4.09(b)(14), RP to §4.07 — with SFA cross-defaults checked for binding constraints." },
    "CP-4C:Definition & Ratio Mechanics Register": { ev: ["E-103"], body: "Ratio mechanics registered: Secured Leverage tested at 4.68x against the 5.25x incurrence ceiling — the 0.57x gap is what prices into $310M of ratio capacity." },
    "CP-4C:Headroom Table": { body: "Headroom table: secured leverage 0.57x, springing covenant 28% (untested), RP build rate ~$45M / year — all current as of the Q1-26 certificate." },
    "CP-4C:Debt / Lien / Priming Analysis": { ev: ["E-63"], body: "Priming risk MEDIUM-HIGH: the full $612M is incurrable pari or senior to the 2L; after the MFN sunset it can also price freely. The 2L is the natural priming victim." },
    "CP-4C:RP / Leakage Analysis": { body: "Leakage paths: the $240M builder basket (pre-positioned, no stated use) plus starter baskets ≈ $310M of total day-one RP capacity — enough for a meaningful dividend without amendment." },
    "CP-4C:Leakage & Basket Flags": { body: "Two flags raised: builder-basket pre-positioning (a behavioral signal, fed to CP-2D) and grower-basket linkage to uncapped add-back EBITDA (mechanical inflation)." },
    "CP-4C:Capacity Risk Priority Matrix": { body: "The priority matrix ranks the MFN sunset first (time-bound), RP activation second (behavioral), and add-back inflation third (gradual) — an ordering inherited by the trigger set." },
    "CP-4C:Gaps Ledger": { body: "No gaps. The capacity math is reproducible end-to-end from registered clause cites." },
    "CP-4C:Overall Covenant Capacity View": { body: "Capacity is the credit's defining legal feature: $612M of day-one debt and $240M+ of leakage — all priced via sizing and triggers rather than exclusion." },

    /* ---- CP-5 · QA & Governance ---- */
    "CP-5:Input Module Register": { body: "All 21 module outputs registered with version hashes at audit start; no stale versions found anywhere in the consumption graph." },
    "CP-5:Math / Logic / Definition Audit": { body: "Every calc-register figure recomputed independently: 0 math defects and 0 instances of definitional drift across 41 KPIs and all derived tables." },
    "CP-5:Legal / Structural Claim Audit": { body: "All legal claims traced to executed-document clauses: capacity math, MFN mechanics and ranking statements verified verbatim against the credit agreement. Clean." },
    "CP-5:RV / Market Claim Audit": { ev: ["E-71"], body: "Market claims verified against LoanX marks and desk runs: the +388 DM, the 96.40 last mark and the fair-band regression inputs all reproduce. Clean." },
    "CP-5:Consistency & Version Audit": { body: "Cross-module consistency clean after the QA-122 rounding fix: every module quotes identical figures for EBITDA, leverage and capacity." },
    "CP-5:Committee-Readiness Audit": { body: "Pack HELD: clearance policy bars committee assembly while any HIGH citation defect is open. All non-citation readiness criteria pass." },
    "CP-5:Export & Evidence Trace Audit": { body: "Export audit clean: all 1,142 citations resolve to registered E-ids; no orphaned or fabricated anchors; master-index hashes match." },
    "CP-5:Remediation Priority Map": { ev: ["E-44"], body: "A single remediation, R-1: re-anchor E-44 to conformed CIM p.391, re-run CP-1C alignment, then refresh the CP-3 RV table and the CP-6A weighting row. Estimated 40 minutes of module time." },

    /* ---- CP-5B · Traceability ---- */
    "CP-5B:Source Register & Readiness": { body: "Gate PASS — consumes the committee-pack figure set and the master evidence index; READY." },
    "CP-5B:Top-5 Material Credit Drivers": { body: "Drivers selected by decision-weight, not narrative prominence: add-back quality, OEM concentration, incremental capacity, FCF conversion, and the contested peer-margin set." },
    "CP-5B:Traceability Map": { body: "The full map is drawn figure-by-figure: every committee-pack number resolves to a producing module, a calc-register entry and a source anchor." },
    "CP-5B:Source Lineage Register": { body: "Lineage chains published for all five drivers, averaging 3.0 hops to a grade-A source; chain confidence ranges 41–97%." },
    "CP-5B:Calculation & Assumption Register": { body: "All assumptions surfaced: four [Analyst estimate] labels in the pack (derived Q4-25, two catalyst probabilities, the maintenance-capex split) — each flagged at point of use." },
    "CP-5B:Gaps Ledger": { body: "No new gaps. The E-44 weak chain is owned by CP-5 remediation R-1 and is not re-logged here." },
    "CP-5B:Overall Traceability View": { body: "Auditability STRONG: four of five chains reach grade-A sources within three hops, and any material figure reconstructs in under two minutes from the master index." },

    /* ---- CP-6A · IC Debate ---- */
    "CP-6A:IC Debate Source Gate": { body: "Gate PASS at the J1 join — all analytical feeders landed. Limitation L-04 is surfaced to the Chair so macro claims carry the unhedged caveat." },
    "CP-6A:Pre-Debate Thesis Map": { body: "The thesis map fixes the contested ground before argument: EBITDA quality, documentation capacity, aftermarket durability, the RV signal and macro exposure — five claims, no strawmen." },
    "CP-6A:Bull Opening Statement": { ev: ["E-12", "E-22"], body: "The bull opens on three claims: an annuity-grade aftermarket (44% of gross profit), top-quartile FCF conversion, and +48–63bps of model cheapness at entry." },
    "CP-6A:Bear Cross-Examination": { ev: ["E-87", "E-63"], body: "The bear attacks on four: add-backs are structural not episodic (recurrence in 3 of the last 4 years), $612M of priming capacity, the sponsor's recap record, and the E-44 hole in the RV case." },
    "CP-6A:Bull Defense": { ev: ["E-44"], body: "The bull defends three of four and concedes E-44: the RV claim is restated on the ex-E-44 band (+20–25bps). The concession is registered in the matrix, not buried." },
    "CP-6A:Debate Resolution Matrix": { body: "The matrix closes all five claims: two to the bear (quality, documentation), one to the bull (aftermarket), one split (RV, pending QA-117), one carried with caveat (macro, under L-04)." },
    "CP-6A:IC Chair Final Memo": { body: "Chair memo: CONSTRUCTIVE at a price — haircut base EBITDA by $35M, treat the documents as the real risk, and let the Q3-26 certificate decide the upgrade to max size." },
    "CP-6A:Gaps Ledger": { body: "One debate-level gap: hedging posture unknown (L-04) — flagged as unresolvable until G-01 lands, rather than argued past." },

    /* ---- CP-6E · Sizing Debate ---- */
    "CP-6E:Portfolio Debate Source Gate": { body: "Gate PASS — the CP-6A verdict, CP-3C fit register and live limit utilization loaded. The debate runs on the IC-approved credit case only." },
    "CP-6E:Pre-Debate Portfolio Thesis Map": { body: "The thesis map narrows to the sizing question: carry-adjusted return vs bucket utilization, correlation overlap, and the E-44-dependent entry signal." },
    "CP-6E:RV Trader's Pitch": { ev: ["E-71"], body: "The trader pitches max size immediately: +388 entry clears the hurdle hold-to-maturity, two-way market depth supports the build, and the catalyst calendar is front-loaded." },
    "CP-6E:Compliance Officer's Attack": { body: "Compliance attacks on three fronts: the B3-or-below bucket at 91% utilization, the open E-44 dependency inside the entry band, and SXAA cluster overlap." },
    "CP-6E:RV Trader's Defense": { body: "The trader concedes staging and proposes the standing constraint: 75bps now, max gated on T-1 plus a same-day bucket re-test — adopted into the decision." },
    "CP-6E:CIO Evidence Weighting": { body: "The CIO weights the three contested points: bucket constraint upheld (compliance), entry validity split (size off the ex-E-44 band), correlation managed (no concurrent SXAA adds)." },
    "CP-6E:Allocation Decision Matrix": { body: "The decision matrix is published with each contested point, both positions and the CIO ruling — the artifact CP-5 audits for decision traceability." },
    "CP-6E:CIO Final Memo": { body: "Memo: approve 75bps at +388 or wider with a standing limit order at +400; the path to 125bps runs through T-1 and bucket headroom; trim discipline wired to T-4 and any re-rank." },
    "CP-6E:Gaps Ledger": { body: "No sizing-level gaps. Bucket utilization is marked T+1 stale and re-tested on trade date by rule." },
  };

export const STEP_NOTES: Record<string, StepNote> = { ...BASE, ...EXT };
