"""vector_embeddings

Revision ID: fb2488db06e3
Revises: 0029
Create Date: 2026-07-06 17:32:43.857946
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import database

# revision identifiers, used by Alembic.
revision: str = 'fb2488db06e3'
down_revision: Union[str, None] = '0029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunk_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chunk_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('vector', database.SafeVector(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunk_embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_chunk_embeddings_lookup', ['model', 'chunk_hash'], unique=True)
        batch_op.create_index('ix_chunk_embeddings_vector', ['vector'], unique=False, postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})
        batch_op.create_index(batch_op.f('ix_document_chunk_embeddings_chunk_hash'), ['chunk_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunk_embeddings_model'), ['model'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunk_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunk_embeddings_model'))
        batch_op.drop_index(batch_op.f('ix_document_chunk_embeddings_chunk_hash'))
        batch_op.drop_index('ix_chunk_embeddings_vector', postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})
        batch_op.drop_index('ix_chunk_embeddings_lookup')

    op.drop_table('document_chunk_embeddings')
    # ### end Alembic commands ###
