// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../../../src/app/command/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/command">> = Specific
  const handler = {} as typeof import("../../../../../src/app/command/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/decisions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/decisions">> = Specific
  const handler = {} as typeof import("../../../../../src/app/decisions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/deepdive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deepdive">> = Specific
  const handler = {} as typeof import("../../../../../src/app/deepdive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/issuers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/issuers">> = Specific
  const handler = {} as typeof import("../../../../../src/app/issuers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/issuers/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/issuers/profile">> = Specific
  const handler = {} as typeof import("../../../../../src/app/issuers/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/model/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/model">> = Specific
  const handler = {} as typeof import("../../../../../src/app/model/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitor">> = Specific
  const handler = {} as typeof import("../../../../../src/app/monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline">> = Specific
  const handler = {} as typeof import("../../../../../src/app/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/portfolios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolios">> = Specific
  const handler = {} as typeof import("../../../../../src/app/portfolios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/query/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/query">> = Specific
  const handler = {} as typeof import("../../../../../src/app/query/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../../../../src/app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/research">> = Specific
  const handler = {} as typeof import("../../../../../src/app/research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/sector-rv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sector-rv">> = Specific
  const handler = {} as typeof import("../../../../../src/app/sector-rv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/sector/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sector">> = Specific
  const handler = {} as typeof import("../../../../../src/app/sector/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/sponsors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sponsors">> = Specific
  const handler = {} as typeof import("../../../../../src/app/sponsors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/upload">> = Specific
  const handler = {} as typeof import("../../../../../src/app/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
